//
//  GetWeatherInteractor.swift
//  SimplyWeather
//
//  Created by Bhat, Nanda on 3/26/17.
//  Copyright (c) 2017 Bhat, Nanda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol GetWeatherInteractorInput
{
    func getWeatherUpdate(request: GetWeather.Location.Request)
}

protocol GetWeatherInteractorOutput
{
    func presentWeather(response: GetWeather.Location.Response)
    
}

class GetWeatherInteractor: GetWeatherInteractorInput
{
    var output: GetWeatherInteractorOutput!
  
    var cityForRequest = ""
    var temperatureForRequest = ""
    var isFarenheit = false
    
  // MARK: - Business logic
  
    func getWeatherUpdate(request: GetWeather.Location.Request) {
        print ("intera")
        print (request.latitude)
        print (request.longitude)
        self.isFarenheit = request.isFarenheit
        let weatherAPI = WeatherAPI()
        weatherAPI.setLatAndLong(latitude: request.latitude, longitude: request.longitude)
        weatherAPI.getWeather(didReceive: didReceiveWeather)
    }
    
    func didReceiveWeather(city: String?, temperature: String?) -> Void{
        print ("did receive")
        print (temperature)
        let response = GetWeather.Location.Response(city: city!, temperature: temperature!, isFarenheit: self.isFarenheit)
        
        // NOTE: Pass the result to the Presenter
        
        output.presentWeather(response: response)

    }
    
    

}
