//
//  GetWeatherConfigurator.swift
//  SimplyWeather
//
//  Created by Bhat, Nanda on 3/26/17.
//  Copyright (c) 2017 Bhat, Nanda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension GetWeatherViewController: GetWeatherPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension GetWeatherInteractor: GetWeatherViewControllerOutput
{
}

extension GetWeatherPresenter: GetWeatherInteractorOutput
{
}

class GetWeatherConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = GetWeatherConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: GetWeatherViewController)
  {
    let router = GetWeatherRouter()
    router.viewController = viewController
    
    let presenter = GetWeatherPresenter()
    presenter.output = viewController
    
    let interactor = GetWeatherInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
